# Generated by Django 4.0.1 on 2022-01-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_id',
        ),
    ]
