# Generated by Django 4.0.1 on 2022-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0002_remove_student_stu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('Dob', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
