# Generated by Django 4.0.1 on 2022-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0003_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
