# Generated by Django 4.0.1 on 2022-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0004_studentdetails_gender_alter_studentdetails_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
