# Generated by Django 4.0.1 on 2022-01-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0007_alter_studentdetails_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('assignment_num', models.IntegerField()),
                ('many_students', models.ManyToManyField(to='studentapi.StudentDetails')),
            ],
        ),
    ]
