# Generated by Django 4.0.1 on 2022-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0009_alter_assignment_assignment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
