# Generated by Django 4.0.1 on 2022-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0010_alter_assignment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
