# Generated by Django 4.0.1 on 2022-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0011_alter_assignment_assignment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
