# Generated by Django 4.0.1 on 2022-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0012_alter_studentdetails_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
