# Generated by Django 4.0.1 on 2022-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0013_alter_studentdetails_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
